/// Flutter icons ButtonIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ButtonIcons
///      fonts:
///       - asset: fonts/ButtonIcons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
import 'package:flutter/widgets.dart';

class ButtonIcons {
  ButtonIcons._();

  static const _kFontFam = 'ButtonIcons';
  static const String? _kFontPkg = null;

  static const IconData arrow_back = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_circle_outline = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_applications = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
