# Generated by Django 4.0 on 2022-01-03 18:38

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='x_created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=None, verbose_name='x_created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='x_modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='x_modified'),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='user'),
        ),
    ]
