# Generated by Django 4.0 on 2022-01-12 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_person_x_created_person_x_modified_alter_person_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
    ]
