# Generated by Django 4.0 on 2022-03-01 14:08

import core.models.type_default_avatar
from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_person_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDefaultAvatar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('x_created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='x_created')),
                ('x_modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='x_modified')),
                ('identifier', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Identifier')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('order', models.IntegerField(default=1, verbose_name='Order')),
                ('image', models.FileField(blank=True, null=True, upload_to=core.models.type_default_avatar.upload_dir_default_avatar, verbose_name='Avatar image')),
            ],
            options={
                'verbose_name': 'Type default avatar',
                'verbose_name_plural': 'Type default avatars',
            },
        ),
    ]
