# Generated by Django 4.0 on 2022-03-01 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_typedefaultavatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typedefaultavatar',
            options={'ordering': ['order'], 'verbose_name': 'Type default avatar', 'verbose_name_plural': 'Type default avatars'},
        ),
    ]
