from .exercise import ExerciseTestCases
from .exercise_api import ExerciseApiTestCases
from .training import TrainingTestCases
from .training_api import TrainingAPITestCases
from .training_plan import TrainingPlanTestCases
from .training_plan_api import TrainingPlanAPITestCases
from .permissions import PermissionsTestCases
from .training_active import TrainingActiveTestCases
from .training_active_api import TrainingActiveAPITestCases
