# Generated by Django 4.0 on 2022-01-21 15:06

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplan',
            name='plan_name',
            field=models.CharField(max_length=128, null=True, verbose_name='Plan name'),
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('x_created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='x_created')),
                ('x_modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='x_modified')),
                ('name', models.CharField(max_length=128, null=True, verbose_name='Training name')),
                ('description', models.CharField(max_length=1024, null=True, verbose_name='Description')),
                ('training_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.trainingplan', verbose_name='Training plan')),
            ],
            options={
                'verbose_name': 'Training',
                'verbose_name_plural': 'Trainings',
            },
        ),
    ]
