# Generated by Django 4.0 on 2022-01-21 15:37

from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_alter_trainingplan_plan_name_training'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOverload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('x_created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='x_created')),
                ('x_modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='x_modified')),
                ('identifier', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Identifier')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('order', models.IntegerField(default=1, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Overload type',
                'verbose_name_plural': 'Overload types',
                'ordering': ['order'],
            },
        ),
    ]
