# Generated by Django 4.0 on 2022-01-21 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_rename_name_training_training_name_exercise'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['order'], 'verbose_name': 'Exercise', 'verbose_name_plural': 'Exercises'},
        ),
    ]
