# Generated by Django 4.0 on 2022-02-27 12:13

from django.db import migrations, models
import workout.models.training_plan


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0009_exercise_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='plan_picture',
            field=models.FileField(blank=True, null=True, upload_to=workout.models.training_plan.upload_dir_plan_picture, verbose_name='Plan picture'),
        ),
    ]
