# Generated by Django 4.0 on 2022-02-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0011_rename_plan_picture_trainingplan_plan_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='default_add_overload_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Default add overload value'),
        ),
    ]
