# Generated by Django 4.0 on 2022-03-28 17:04

from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0012_exercise_default_add_overload_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeExerciseState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('x_created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='x_created')),
                ('x_modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='x_modified')),
                ('identifier', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Identifier')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('order', models.IntegerField(default=1, verbose_name='Order')),
                ('state', models.CharField(blank=True, max_length=32, null=True, verbose_name='State')),
            ],
            options={
                'verbose_name': 'Exercise state',
                'verbose_name_plural': 'Exercise states',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
