# Generated by Django 4.0 on 2022-04-06 14:36

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0013_typeexercisestate_trainingplan_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeExerciseState',
            new_name='TypeTrainingState',
        ),
        migrations.CreateModel(
            name='TrainingActive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('x_created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='x_created')),
                ('x_modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='x_modified')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercises_active', to='workout.typetrainingstate', verbose_name='State')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises_active', to='workout.training', verbose_name='Training')),
            ],
            options={
                'verbose_name': 'Active training',
                'verbose_name_plural': 'Active trainings',
            },
        ),
        migrations.CreateModel(
            name='Overload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('x_created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='x_created')),
                ('x_modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='x_modified')),
                ('value', models.IntegerField(verbose_name='Value')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.exercise', verbose_name='Exercise')),
                ('training_active', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overloads', to='workout.trainingactive', verbose_name='Training active')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.typeoverload', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Overload',
                'verbose_name_plural': 'Overloads',
            },
        ),
    ]
