# Generated by Django 4.0 on 2022-04-06 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0014_rename_typeexercisestate_typetrainingstate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overload',
            options={'ordering': ['-order'], 'verbose_name': 'Overload', 'verbose_name_plural': 'Overloads'},
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='overload_history',
        ),
        migrations.RemoveField(
            model_name='overload',
            name='type',
        ),
        migrations.AddField(
            model_name='overload',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='overload',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overloads', to='workout.exercise', verbose_name='Exercise'),
        ),
    ]
