# Generated by Django 4.0 on 2022-04-06 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0015_alter_overload_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typetrainingstate',
            name='state',
        ),
        migrations.AlterField(
            model_name='trainingactive',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainings_active', to='workout.typetrainingstate', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='trainingactive',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings_active', to='workout.training', verbose_name='Training'),
        ),
    ]
