# Generated by Django 4.0 on 2022-04-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0016_remove_typetrainingstate_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overload',
            name='value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Value'),
        ),
    ]
