# Generated by Django 4.0 on 2022-04-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0017_alter_overload_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overload',
            options={'ordering': ['order'], 'verbose_name': 'Overload', 'verbose_name_plural': 'Overloads'},
        ),
        migrations.AlterField(
            model_name='exercise',
            name='default_add_overload_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Default add overload value'),
        ),
    ]
