# Generated by Django 4.0 on 2022-04-13 16:18

from django.db import migrations, models
import django_extensions.db.fields
import uuid
import workout.models.default_plan_image


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0018_alter_overload_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultPlanImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('x_created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='x_created')),
                ('x_modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='x_modified')),
                ('image', models.FileField(blank=True, null=True, upload_to=workout.models.default_plan_image.upload_dir_default_plan_picture, verbose_name='Default picture')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='trainingactive',
            options={'ordering': ('x_modified',), 'verbose_name': 'Active training', 'verbose_name_plural': 'Active trainings'},
        ),
        migrations.AlterModelOptions(
            name='typetrainingstate',
            options={'ordering': ['order'], 'verbose_name': 'Training state', 'verbose_name_plural': 'Training states'},
        ),
    ]
