# Generated by Django 4.0 on 2022-06-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0019_defaultplanimage_alter_trainingactive_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='overload_unit',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Overload unit'),
        ),
    ]
