# Generated by Django 4.0 on 2022-06-07 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0021_rename_overload_unit_exercise_overload_datatype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='description',
        ),
    ]
