# Generated by Django 4.0 on 2022-06-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0022_remove_training_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeoverload',
            name='data_type',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Data type'),
        ),
    ]
