# Generated by Django 4.0 on 2022-06-07 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0024_rename_typeoverload_overloaddefinition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overloaddefinition',
            name='identifier',
        ),
    ]
