# Generated by Django 4.0 on 2022-06-07 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0025_remove_overloaddefinition_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overloaddefinition',
            name='description',
        ),
    ]
