# Generated by Django 4.0 on 2022-06-07 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0026_remove_overloaddefinition_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overloaddefinition',
            options={'verbose_name': 'Overload type', 'verbose_name_plural': 'Overload types'},
        ),
        migrations.RemoveField(
            model_name='overloaddefinition',
            name='order',
        ),
    ]
