# Generated by Django 4.0 on 2022-06-07 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0027_alter_overloaddefinition_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='overload_type',
            new_name='overload_definition',
        ),
    ]
