# Generated by Django 4.0 on 2022-06-07 07:01

from django.db import migrations, models
import workout.models.types


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0028_rename_overload_type_exercise_overload_definition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overloaddefinition',
            name='data_type',
            field=models.CharField(blank=True, default=workout.models.types.OverloadDataTypes['NUMBER'], max_length=32, null=True, verbose_name='Data type'),
        ),
    ]
