# Generated by Django 4.0 on 2022-06-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0029_alter_overloaddefinition_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overload',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='overloaddefinition',
            name='data_type',
            field=models.CharField(blank=True, default='number', max_length=32, null=True, verbose_name='Data type'),
        ),
    ]
